### ISSUE TITLE
Possible Data Desync

### ISSUE THREAD

**Issue by natemontgomery** [javereec/spree_elasticsearch#11]
Because the Indexable concern uses an after_save hook (https://github.com/javereec/spree_elasticsearch/blob/master/app/models/spree/concerns/indexable.rb#L54), if the changes are rolled back I think you can end up with desynchronized data between db and es.  Shouldn't this be an after_commit hook?

I can do further work to demonstrate my thinking on the possible issue (basically just a transaction wrapping a record update) if you would like, or maybe even a PR (if I wasn't at work I would just go for it).

**Comment by alepore** [comment]
:+1: for this, is clearly suggested here: https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model#custom-callbacks

**Comment by javereec** [comment]
Good point, but in recent versions the indexable concern I wrote in the beginning is obsolete anyway. I now use the `elasticsearch-rails` and `elasticsearch-model` gems which are much better integrated and provide a lot more functionality.

I'll update the README to cover this.
