### ISSUE TITLE
pagination problem

### ISSUE THREAD

**Issue by alepore** [javereec/spree_elasticsearch#12]
Hi,
looks like the per page value of my searches uses the Kaminari config and not what i pass in the query.
Looking at `elasticsearch-rails` doc i think this is actually the right thing: https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model#pagination
So i think this should be more clear in the doc, and there's probably some code that can be removed because changing `size` on `Product::ElasticsearchQuery` has not effect on the query.

a sample query looks like this:
```
  Spree::Product Search (16.3ms) {index: "development", type: "spree_product", body: {query: {filtered: {query: {match_all: {}}, filter: {"and"=>[{term: {:visible?=>true}}, {terms: {taxon_ids: [4]}}]}}}, sort: [{"name"=>{order: "asc"}}, "_score"], 
```
notice last 4 elements: 25 is kaminari default and 30 is what i pass.

thoughts?

**Comment by javereec** [comment]
You're absolutely correct. I noticed this problem also in my shop and I'll fix it asap.
