### ISSUE TITLE
Taxon position sorting

### ISSUE THREAD

**Issue by alepore** [javereec/spree_elasticsearch#15]
The default Spree `Search::Base` behaviour on taxon search is to order products for `position`, see `Product#in_taxon` scope.

If i'm not wrong, we lost this sorting as we use the elasticsearch searcher, right?

Any idea how to add that?

**Comment by javereec** [comment]
You're correct, but it should not be too difficult to add.

* Add `position` to the mapping of the product
* Add `position` to the sorting section of the `ElasticsearchQuery` class

**Comment by alepore** [comment]
ok but we need one position for each taxon...
not sure what's the correct data structure to save those data

**Comment by javereec** [comment]
This will indeed need something else. You could probably get it working with nested objects. Model the taxons as a nested object. It is now possible to sort on the nested objects but there are some quirks involved with this. Look at following play gist for inspiration

https://www.found.no/play/gist/a21d8efdd7996c34c76f

If you get it working, feel free to submit pull request

**Comment by alepore** [comment]
ok thanks, for the moment i think i solved using some code like:

```ruby
      indexes :classifications, type: 'nested', include_in_parent: true do
        indexes :taxon_id, type: 'integer'
        indexes :position, type: 'integer'
      end
```

```ruby
      result[:classifications] = taxons.map do |t|
        classification = classifications.find_by(taxon_id: t.id)
        {
          taxon_id: t.id,
          position: classification.try(:position) || 1000
        }
      end if taxons.any?
```

sorting

```ruby
          [
            {
              "classifications.position" => {
                order: "asc",
                nested_filter: {
                  terms: {
                    "classifications.taxon_id" => taxons
                  }
                }
              }
            },
            {
              "name" => {
                order: "asc"
              }
            }
          ]
```

**Comment by connecticus** [comment]
@alepore thank you for solution, you awesome

**Comment by connecticus** [comment]
Expert help is required. I tried to use this solution with ES6 and it gives me an error: 

> illegal_argument_exception","reason":"Fielddata is disabled on text fields by default

So I dig hard this issue but still no luck, any help is highly appreciated.
