### ISSUE TITLE
err in vanilla spree 2.4

### ISSUE THREAD

**Issue by connecticus** [javereec/spree_elasticsearch#16]
Hi Jan,

thank you for wonderful gem,

but I can't start it in vanilla  spree - got error:

undefined method `response' for #<Spree::Product::ActiveRecord_Relation:0x007fdfbdc26f60>

ActionView::Template::Error (undefined method `response' for #<Spree::Product::ActiveRecord_Relation:0x007fdfbdc26f60>):
    2:   <%= form_tag '', :method => :get, :id => 'sidebar_products_search' do %>
    3:     <% params[:search] ||= {} %>
    4:     <%= hidden_field_tag 'per_page', params[:per_page] %>
    5:     <% facets = process_facets(@products.response.response['facets']) %>
    6:     <%= select_tag "sorting", options_for_select({Spree.t("search_sorting.name_asc") => "name_asc", Spree.t("search_sorting.name_desc") => "name_desc", Spree.t("search_sorting.price_asc") => "price_asc", Spree.t("search_sorting.price_desc") => "price_desc", Spree.t("search_sorting.relevancy") => "score"}, params[:sorting]), :onchange => "this.form.submit();" %>
    7:     <%= render :partial => 'spree/shared/filter_price', :locals => { :facet => facets['price'] } %>
    8:     <%= render :partial => 'spree/shared/filter_properties', :locals => { :facets => facets.select {|key,facet| ((key != "price") && (key != "taxon_ids")) && (facet['_type'] == 'terms')} || [] } %>
  activerecord (4.1.9) lib/active_record/relation/delegation.rb:136:in `method_missing'
  activerecord (4.1.9) lib/active_record/relation/delegation.rb:99:in `method_missing'

**Comment by javereec** [comment]
I strongly suspect you're not assigning the searcher class from the gem. Make sure you add following in the Spree config block

```ruby
Spree.config do |config|
  config.searcher_class = Spree::Search::Elasticsearch
end
```

**Comment by connecticus** [comment]
Yes, I have only recently found your same advice. It work!

Thank U!
