### ISSUE TITLE
undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by connecticus** [javereec/spree_elasticsearch#17]
Hi, Jan, 

now I cant find a causal relationship, but in some taxons I have this issue. May be you have idea?

Regards, Kate.

<%= form_tag '', :method => :get, :id => 'sidebar_products_search' do %>
      <% params[:search] ||= {} %>
      <%= hidden_field_tag 'per_page', params[:per_page] %>
      <% facets = process_facets(@products.response.response['facets']) %>
      <%= select_tag "sorting", options_for_select({Spree.t("search_sorting.name_asc") => "name_asc", Spree.t("search_sorting.name_desc") => "name_desc", Spree.t("search_sorting.price_asc") => "price_asc", Spree.t("search_sorting.price_desc") => "price_desc", Spree.t("search_sorting.relevancy") => "score"}, params[:sorting]), :onchange => "this.form.submit();" %>
      <%= render :partial => 'spree/shared/filter_price', :locals => { :facet => facets['price'] } %>
      <%= render :partial => 'spree/shared/filter_properties', :locals => { :facets => facets.select {|key,facet| ((key != "price") && (key != "taxon_ids")) && (facet['_type'] == 'terms')} || [] } %>

**Comment by javereec** [comment]
Probably a masterdata issue. Maybe property of a product with blank name or value. I would start looking in the `process_facet` method.

**Comment by connecticus** [comment]
Jan, thank you. 

Yes, some properties fields is blank. Perhaps there is a reason to put the protection against such errors?

**Comment by connecticus** [comment]
ok, newermind,

thank you!
