### ISSUE TITLE
IndexMissingException[[development] missing]" spree elasticsearch

### ISSUE THREAD

**Issue by joshuawatson** [javereec/spree_elasticsearch#22]
I have getting this error.

Showing /home/project/.rvm/gems/ruby-2.2.1/gems/spree_frontend-3.0.0/app/views/spree/home/index.html.erb where line #8 raised:

[404] {"error":"IndexMissingException[[development] missing]","status":404}
Extracted source (around line #135):
              
        def __raise_transport_error(response)
          error = ERRORS[response.status] || ServerError
          raise error.new "[#{response.status}] #{response.body}"
        end

elasticseach.yml file 

defaults: &defaults
  hosts: localhost
  port: '9200'
  bootstrap: true

development:
  <<: *defaults
  index: development

**Comment by javereec** [comment]
I believe I removed bootstrapping, because I couldn't get it right. What I personally do is include the following block of code in my `config/application.rb` file, inside the `to_prepare` block. This allows for fine grained control in setting up your index. Hope this helps.

```ruby
    config.to_prepare do
      # Load application's model / class decorators
      Dir.glob(File.join(File.dirname(__FILE__), "../app/**/*_decorator*.rb")) do |c|
        Rails.configuration.cache_classes ? require(c) : load(c)
      end

      # Load application's view overrides
      Dir.glob(File.join(File.dirname(__FILE__), "../app/overrides/*.rb")) do |c|
        Rails.configuration.cache_classes ? require(c) : load(c)
      end

      unless Elasticsearch::Model.client.indices.exists index: Spree::ElasticsearchSettings.index
        Elasticsearch::Model.client.indices.create \
          index: Spree::ElasticsearchSettings.index,
          body: {
            settings: {
              number_of_shards: 1,
              number_of_replicas: 0,
              analysis: {
                analyzer: {
                   nGram_analyzer: {
                      type: "custom",
                      filter: ["lowercase", "asciifolding", "nGram_filter"],
                      tokenizer: "whitespace" },
                   whitespace_analyzer: {
                      type: "custom",
                      filter: ["lowercase", "asciifolding"],
                      tokenizer: "whitespace" }},
                filter: {
                   nGram_filter: {
                      max_gram: "20",
                      min_gram: "3",
                      type: "nGram",
                      token_chars: ["letter", "digit", "punctuation", "symbol"] }}}},
            mappings: Spree::Product.mappings.to_hash }
      end
    end

    require 'elasticsearch/rails/lograge'
```

**Comment by joshuawatson** [comment]
When i search the product it show empty list

**Comment by javereec** [comment]
- Are the products in the index (bundle exec rake spree:elasticsearch)?
- Does the elasticsearch query return anything if you run it directly
against the ES cluster?

Jan Vereecken
Clubit bvba
janvereecken@clubit.be

**Comment by javereec** [comment]
Query looks ok.
