### ISSUE TITLE
Allow option for execution mode on terms filter

### ISSUE THREAD

**Issue by jspizziri** [javereec/spree_elasticsearch#25]
It would be nice to allow the setting of the execution mode on the terms filter. For ex.

```json
{
    "query": {
        "filtered": {
            "query": {
                "match_all": {}
            },
            "filter": {
                "and": [
                    { 
                        "terms": { 
                            "taxon_ids": [3,45],
                            "execution": "and"
                        } 
                    }
                ]
            }
        }
    }
}
```

**Comment by javereec** [comment]
You can do that. I suggest you decorate the inner class to you own liking. My experience is that each project requires other search queries, therefore you can use the class provided by the extension as inspiration and extend on that.

Create a file `product_elasticsearch_decorator.rb`

and fill it up

````ruby
module Spree
  Product::ElasticsearchQuery.class_eval do
    def to_hash
      # the most marvellous query
    end
  end
end````

**Comment by jspizziri** [comment]
Thanks for the reply.

I realize that I can override the `to_hash` method; however, to do so would would loose the possibility of getting the updates provided in this gem. For instance, hopefully an update for elasticsearch 2.0 once elasticsearch-model catches up.
