### ISSUE TITLE
less frontend requirements

### ISSUE THREAD

**Issue by alepore** [javereec/spree_elasticsearch#9]
hi, i'm trying this extension and looks good, thanks!
one thing i don't like is that it's pretty invasive on the frontend side.

specifically, the complete override of a very important template as `_products` and the inclusion of the whole `skeleton` css.
both things are not suitable for my stores, for example: i use a custom bootstrap frontend.
wha do you think?

p.s:
i think my `_products` works well even without that `product.id` tweak, possible?

**Comment by javereec** [comment]
I removed the _product partial override.

The remarks for css and js stay applicable.
